"""empty message

Revision ID: af02e38902c1
Revises: 
Create Date: 2021-07-28 16:27:54.328360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af02e38902c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('starttime', sa.String(length=150), nullable=True),
    sa.Column('stoptime', sa.String(length=150), nullable=True),
    sa.Column('bikeid', sa.String(length=150), nullable=True),
    sa.Column('from_station_id', sa.String(length=150), nullable=True),
    sa.Column('from_station_name', sa.String(length=150), nullable=True),
    sa.Column('to_station_id', sa.String(length=150), nullable=True),
    sa.Column('to_station_name', sa.String(length=150), nullable=True),
    sa.Column('usertype', sa.String(length=150), nullable=True),
    sa.Column('gender', sa.String(length=150), nullable=True),
    sa.Column('birthday', sa.String(length=150), nullable=True),
    sa.Column('trip_duration', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('trip_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
